### ISSUE TITLE
Defer cross-domain iframe loads until they are viewable

### ISSUE THREAD

**Issue by KenjiBaheux** [WICG/interventions#10] opened 2016-03-02 03:25 UTC
Deferring the load of out-of-view iframes should improve the Loading user experience (more bandwidth & cpu for assets and tasks that are more essential than out-of-view iframes).

To make this intervention safer, it might make sense to restrict its scope to cross-domain iframes.

To strike the right balance between the needs of iframe owners and the user experience, it might be important to time the load on "about to be viewable" / "not viewable yet but idle time" signals rather than a strict "became viewable" signal.

**Comment by bsittler** [comment] 2016-04-25 18:43
Some sites using off-screen IFRAMEs for cross-origin APIs using postMessage, for instance to facilitate OAuth 2 and other authorization checks and for CORS-like API calling with additional client-side features (caching, auth token injection, etc.) These "service" IFRAMEs are typically positioned absolutely at negative x and/or y coordinates. Is there any way to avoid breaking them?

**Comment by KenjiBaheux** [comment] 2016-04-25 23:50
Thinking out loud: 
 1. iframes that are meant to always be offscreen vs.
 2. iframes that are currently offscreen but could be reached out

We could ignore case 1 iframes?

**Comment by hillbrad** [comment] 2016-09-29 15:56
Agreed.  

This would be horrible to apply to same-origin iframes, as they are used by many AJAX type frameworks to parallelize and do background loads of content.  Much of Facebook works like this. (yes you could do this today with Workers, but this strategy is more broadly compatible and has worked much longer than Workers have been around)

For cross-origin cases, iframes and postMessage are the safest and best cross-origin communication mechanism we have.  This would be really unfortunate for the platform.  We *want* developers to do things like this instead of expensive HTTP round-trips using easily abused open redirectors. There a number of ways these iframes are deliberately hidden: display: none, 0x0 size, or positioned off-screen.

Could we have a "nice" attribute instead so that page authors could give explicit scheduling priorities to iframe loads?

**Comment by ojanvafai** [comment] 2016-09-29 16:35
This is something we'll need to experiment with. It's not clear to me we'll every find something shippable here, but the problem is (maybe) big enough to warrant investigation. To start with, we're just measuring the number of cross-origin frames that are never visible. I think there's a few obvious things we'll need to exclude from that though:
-Same-origin frames. Sync access to the parent page makes them more likely to be needed. 
-0x0 frames. Clearly the majority of these will be used for some sort of postMessage conversation.
-Frames that are in user inaccessible regions of the page (i.e. above the top or to the left of the scrollable region of the root of the page). Clearly the majority of these will be used for some sort of postMessage conversation.

**Comment by Daniel15** [comment] 2016-09-29 17:35
Is this a duplicate of #1?

**Comment by ojanvafai** [comment] 2017-07-17 19:26
It's not a dupe. #1 still loads them, just at a lower priority. This proposal is oriented at both performance benefits and reduction in bytes downloaded, so doesn't load them at all if they're far from the viewport.

**Comment by Malvoz** [comment] 2019-08-24 14:37
The [`loading` attribute](https://github.com/whatwg/html/pull/3752) and the `Feature-Policy` HTTP header field's policy-controlled features [`loading-frame-default-eager`](https://github.com/w3c/webappsec-feature-policy/blob/master/policies/loading-frame-default-eager.md) and [`loading-image-default-eager`](https://github.com/w3c/webappsec-feature-policy/blob/master/policies/loading-image-default-eager.md) allows for developers to control the loading of iframes and images(#15).

I presume this addition of native lazy-loading resolves this issue, and #15.

<hr>

The default behavior of the `loading` attribute (between `auto|lazy|eager`) is `auto`, meaning a browser can defer the loading of the frame/img when `eager` isn't specified, but there are concerns (e.g. @bsittler's https://github.com/WICG/interventions/issues/10#issuecomment-214475422) around browsers deferring these elements when that isn't desired. While I don't think this behavior of "allowing hidden iframes" is something that would end up in the spec, there are heuristics such as [Blink's Lazy Frames](https://docs.google.com/document/d/1ITh7UqhmfirprVtjEtpfhga5Qyfoh78UkRmW8r3CntM) to allow for that desired behavior.

**Comment by johannhof** [comment] 2022-04-25 13:58
(As noted in https://github.com/WICG/interventions/pull/72, we intend to archive this repository and are thus triaging and resolving all open issues)

This seems quite an ambitious effort considering the outlined use-cases that would be broken. There may be potential for browser experimentation, and, if it proves successful, the following standardization discussion could be had in a new issue on HTML.

There is also the (optional) [`loading` attribute](https://developer.mozilla.org/en-US/docs/Web/Performance/Lazy_loading#images_and_iframes) which helps sites opt-in to this behavior with less risk of breakage.

**Closed by johannhof** 2022-04-25 13:58 UTC
Labels: Chrome-P1
