### ISSUE TITLE
Pause background tabs on desktop

### ISSUE THREAD

**Issue by anirudhcmohan** [WICG/interventions#54] opened 2017-07-18 19:44 UTC

**Comment by johannhof** [comment] 2022-05-17 14:33
(As noted in https://github.com/WICG/interventions/pull/72, we intend to archive this repository and are thus triaging and resolving all open issues)

This seems to be a dupe of #7 (or doesn't contain enough context so suggest otherwise)

**Closed by johannhof** 2022-05-17 14:33 UTC
Labels: Chrome-P1
